@startuml

package "Cadastro" {

  class Competicao
  class Atleta
  class Pais

}

package "Alocacao" {

  class Local

}

package "Resultados" {

  class Resultado

}

package "Relatorios" {

  class RelatorioMedalhas

}

package "Interface" {

  class TelaCompeticoes
  class TelaResultados
  class TelaRelatorios

}

Cadastro ..> Alocacao
Cadastro ..> Resultados
Resultados ..> Relatorios
Interface ..> Cadastro
Interface ..> Relatorios

@enduml