@startuml

package "Sistema SGO" {

  [Interface Web]

  [Modulo Competicoes]

  [Modulo Inscricoes]

  [Modulo Alocacao]

  [Modulo Resultados]

  [Modulo Relatorios]

  database "Banco de Dados"

}

[Interface Web] --> [Modulo Competicoes]

[Interface Web] --> [Modulo Relatorios]

[Modulo Competicoes] --> [Modulo Inscricoes]

[Modulo Competicoes] --> [Modulo Alocacao]

[Modulo Competicoes] --> [Modulo Resultados]

[Modulo Resultados] --> [Modulo Relatorios]

[Modulo Competicoes] --> [Banco de Dados]

[Modulo Inscricoes] --> [Banco de Dados]

[Modulo Alocacao] --> [Banco de Dados]

[Modulo Resultados] --> [Banco de Dados]

[Modulo Relatorios] --> [Banco de Dados]

@enduml